steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '$_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$_IMAGE:latest'
      - '.'
    id: Build

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - push 
      - '$_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$_IMAGE:latest'
    id: Push
    waitFor: ['Build']

images:
  - '$_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$_IMAGE:latest'

options:
  logging: CLOUD_LOGGING_ONLY