services:
  life-frontend:
    image: frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: life-frontend
    ports:
      - "3000:3000"
    networks:
      - life-network

networks:
  life-network:
    external: true
    name: life-network